/* Generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "nl-to-sql",
  "name": "SQL Copilot",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "Which five customers spent the most last quarter?",
      "does": "Writes the SQL, runs it on the loaded database and shows the table."
    },
    {
      "say": "Same thing but only for orders shipped late",
      "does": "Edits the previous query with an extra condition and reruns it."
    },
    {
      "say": "Explain what this query is doing",
      "does": "Walks through the current SQL clause by clause."
    }
  ]
};
